### ISSUE TITLE
Add PLATFORMIO_AUTH_TOKEN secret to the repository

### ISSUE THREAD

**Issue by hacker-cb** [hacker-cb/nanopb_cpp#2]
@PetteriAimonen could you please add secret `PLATFORMIO_AUTH_TOKEN` at least to `nanopb_cpp` repository?

Just run `pio account token`, from the console to get token.

I don't have rights to do it by myself :( 
As alternative you can give full rights to the `nanopb_cpp` repository and I will do it by myself.

This is last step to finish CD for the `nanopb_cpp` project.

Thank you in adavance.

**Comment by PetteriAimonen** [comment]
Ah, ok, sorry about that - I didn't realize it didn't automatically make you the admin of this repo.

**Comment by hacker-cb** [comment]
Thank you. :)
